// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_UZXaTju78MPe@ep-empty-cloud-a80clr2o.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require",
  },
});
